services:
  database:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: blogdb
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - type: volume
        source: database-store
        target: /var/lib/postgresql/data
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  database-store:
